#!name=netflix
#!desc=直连Netflix

[Rule]
DOMAIN-SUFFIX,fast.com,DIRECT
DOMAIN-SUFFIX,netflix.com,DIRECT
DOMAIN-SUFFIX,netflix.net,DIRECT
DOMAIN-SUFFIX,netflixdnstest0.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest1.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest2.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest3.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest4.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest5.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest6.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest7.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest8.com,DIRECT
DOMAIN-SUFFIX,netflixdnstest9.com,DIRECT
DOMAIN-SUFFIX,nflxext.com,DIRECT
DOMAIN-SUFFIX,nflximg.com,DIRECT
DOMAIN-SUFFIX,nflximg.net,DIRECT
DOMAIN-SUFFIX,nflxso.net,DIRECT
DOMAIN-SUFFIX,nflxvideo.net,DIRECT
IP-CIDR,8.41.4.0/24,no-resolve,DIRECT
IP-CIDR,23.246.0.0/18,no-resolve,DIRECT
IP-CIDR,37.77.184.0/21,no-resolve,DIRECT
IP-CIDR,45.57.0.0/17,no-resolve,DIRECT
IP-CIDR,64.120.128.0/17,no-resolve,DIRECT
IP-CIDR,66.197.128.0/17,no-resolve,DIRECT
IP-CIDR,69.53.224.0/19,no-resolve,DIRECT
IP-CIDR,108.175.32.0/20,no-resolve,DIRECT
IP-CIDR,185.2.220.0/22,no-resolve,DIRECT
IP-CIDR,185.9.188.0/22,no-resolve,DIRECT
IP-CIDR,192.173.64.0/18,no-resolve,DIRECT
IP-CIDR,198.38.96.0/19,no-resolve,DIRECT
IP-CIDR,198.45.48.0/20,no-resolve,DIRECT
IP-CIDR,207.45.72.0/22,no-resolve,DIRECT
IP-CIDR,208.75.76.0/22,no-resolve,DIRECT


[Host]
*.fast.com = 103.152.34.236
*.netflix.com = 103.152.34.236
*.netflix.net = 103.152.34.236
*.netflixdnstest0.com = 103.152.34.236
*.netflixdnstest1.com = 103.152.34.236
*.netflixdnstest2.com = 103.152.34.236
*.netflixdnstest3.com = 103.152.34.236
*.netflixdnstest4.com = 103.152.34.236
*.netflixdnstest5.com = 103.152.34.236
*.netflixdnstest6.com = 103.152.34.236
*.netflixdnstest7.com = 103.152.34.236
*.netflixdnstest8.com = 103.152.34.236
*.netflixdnstest9.com = 103.152.34.236
*.nflxext.com = 103.152.34.236
*.nflximg.com = 103.152.34.236
*.nflximg.net = 103.152.34.236
*.nflxso.net = 103.152.34.236
*.nflxvideo.net = 103.152.34.236
